export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_MOVIES_SUCCES = 'FETCH_MOVIES_SUCCES';
export const FETCH_MOVIES_ERROR = 'FETCH_MOVIES_ERROR';
export const SELECT_MOVIE = 'SELECT_MOVIE';
