export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_MOVIES_SUCCES = 'FETCH_MOVIES_SUCCES';
export const FETCH_MOVIES_ERROR = 'FETCH_MOVIES_ERROR';

export const FETCH_CHARACTER = 'FETCH_CHARACTER';
export const FETCH_CHARACTER_SUCCES = 'FETCH_CHARACTER_SUCCES';
export const FETCH_CHARACTER_ERROR = 'FETCH_CHARACTER_ERROR';
